# Generated by Django 3.0.4 on 2020-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=10000)),
                ('image', models.ImageField(default='uploads/None/no-img.jpg', upload_to='uploads/news/')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='uploads/None/no-img.jpg', upload_to='uploads/film_poster/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
