# Generated by Django 3.0.4 on 2020-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_auto_20200323_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
