# Generated by Django 3.0.4 on 2020-03-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новини'},
        ),
    ]
