# Generated by Django 3.0.4 on 2020-03-24 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_auto_20200323_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='show_from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='show_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='show_to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='show_today',
            field=models.BooleanField(default=False),
        ),
    ]
