# Generated by Django 3.0.4 on 2020-03-24 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_auto_20200324_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='show_from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='film',
            name='show_to_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
