# Generated by Django 3.0.4 on 2020-03-24 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_auto_20200324_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='show_from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='show_to_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
