# Generated by Django 3.0.4 on 2020-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0008_auto_20200324_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='show_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='show_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
