# Generated by Django 3.0.4 on 2020-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_auto_20200324_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='can_sell_ticket',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
