# Generated by Django 3.0.4 on 2020-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_film_can_sell_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='can_sell_ticket',
            field=models.BooleanField(default=True),
        ),
    ]
