# Generated by Django 3.0.4 on 2020-03-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0013_auto_20200324_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='show_now_from_date',
            new_name='show_soon_to_date',
        ),
    ]
