# Generated by Django 3.0.4 on 2020-03-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0015_film_show_now_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='show_now_duration',
            field=models.DurationField(blank=True, help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', null=True),
        ),
        migrations.CreateModel(
            name='FilmShowDuratiun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('till', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Film')),
            ],
        ),
    ]
