# Generated by Django 3.0.4 on 2020-03-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0016_auto_20200324_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmShowSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.DateTimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Film')),
            ],
        ),
        migrations.DeleteModel(
            name='FilmShowDuratiun',
        ),
    ]
