# Generated by Django 3.0.4 on 2020-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0017_auto_20200324_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='show_now_duration',
        ),
    ]
