# Generated by Django 3.0.4 on 2020-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0018_remove_film_show_now_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmshowsession',
            name='three_d',
            field=models.BooleanField(default=True, verbose_name='3D сеанс'),
        ),
    ]
