# Generated by Django 3.0.4 on 2020-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0019_filmshowsession_three_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmshowsession',
            name='hall',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
