# Generated by Django 3.0.4 on 2020-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0020_filmshowsession_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmshowsession',
            name='hall',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
