# Generated by Django 3.0.4 on 2020-03-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0023_auto_20200325_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmdescription',
            old_name='operator',
            new_name='producer',
        ),
    ]
