# Generated by Django 3.0.4 on 2020-03-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0024_auto_20200325_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmdescription',
            name='operator',
            field=models.CharField(default='gr', max_length=150),
        ),
    ]
