# Generated by Django 3.0.4 on 2020-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0028_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата додавання новини'),
        ),
    ]
